/**
 * Pinned download for every engine, per platform.
 *
 * GENERATED by `generate-engine-pins.mjs` — regenerate rather than edit. It is
 * 14 artifacts and ~5 GB of hashing, and a mistyped digit fails an install with
 * a checksum error that names nothing.
 *
 * Kept beside `slicer-targets.mjs` and keyed by the same ids, so the container's
 * baked-in set and the runtime-installable set cannot drift into two lists that
 * disagree about which engines exist.
 *
 * Two invariants the generator enforces, both easy to break by hand:
 *
 * - The LINUX url matches whatever `slicer-targets.mjs` already points at.
 *   Releases ship several AppImages differing only in Ubuntu base, and the base
 *   sets the glibc floor — "upgrading" 2.6.0.51 from ubuntu-22.04 to 24.04 while
 *   recording a checksum would change what existing installs run under cover of
 *   a pinning change.
 * - The WINDOWS url is the portable zip, never the installer .exe: no elevation,
 *   no registry, and it unpacks with the yauzl already in the tree.
 */
export const ENGINE_ASSETS = {
  'bambustudio-2-6-0-51': {
    'linux-x64': {
      url: 'https://github.com/bambulab/BambuStudio/releases/download/v02.06.00.51/BambuStudio_ubuntu-22.04-v02.06.00.51-20260417160415.AppImage',
      sha256: 'e73ed73bd32c3fb9b75cf152b4e6936f5d24ec2f1ac2a788fd8aeb162877af46',
      bytes: 223988216
    },
    'win32-x64': {
      url: 'https://github.com/bambulab/BambuStudio/releases/download/v02.06.00.51/Bambu_Studio_win-v02.06.00.51-20260417160415.zip',
      sha256: 'aa401dd6e848a986cff17b4a07b4af774ecf3c588e2faaec660f96d21657373c',
      bytes: 426009578
    },
  },
  'bambustudio-2-6-1-55': {
    'linux-x64': {
      url: 'https://github.com/bambulab/BambuStudio/releases/download/v02.06.01.55/BambuStudio_ubuntu22.04-v02.06.01.55-20260429100944.AppImage',
      sha256: '5483a6b1bd87121b7e7f44aa4ae1848b09cdaf522d5558be5c47bc58cb61a079',
      bytes: 224864760
    },
    'win32-x64': {
      url: 'https://github.com/bambulab/BambuStudio/releases/download/v02.06.01.55/Bambu_Studio_win-v02.06.01.55-20260428201229.zip',
      sha256: 'ace930e08b3c3770d2072a380713b7255230418f4438c98442dae9355e2d1399',
      bytes: 446235247
    },
  },
  'bambustudio-2-7-0-55': {
    'linux-x64': {
      url: 'https://github.com/bambulab/BambuStudio/releases/download/v02.07.00.55/BambuStudio_ubuntu-22.04-v02.07.00.55-20260514170313.AppImage',
      sha256: 'ae245a8beada183f5a2a15ae1710b4bab9d9f5264dd1e8627d65a8d212e44be7',
      bytes: 226769400
    },
    'win32-x64': {
      url: 'https://github.com/bambulab/BambuStudio/releases/download/v02.07.00.55/Bambu_Studio_win-v02.07.00.55-20260514170313.zip',
      sha256: '2bcd353ecddb24d8448cf308216777f73e2d2461b438d0a2519c781605ec3598',
      bytes: 455121623
    },
  },
  'bambustudio-2-7-1-57': {
    'linux-x64': {
      url: 'https://github.com/bambulab/BambuStudio/releases/download/v02.07.01.57/BambuStudio_ubuntu-24.04-v02.07.01.57-20260601192128.AppImage',
      sha256: '85b053853f1a238775cd7ae2d4d19544e35260592428d2276ca27dcbd5f8eb53',
      bytes: 227875320
    },
    'win32-x64': {
      url: 'https://github.com/bambulab/BambuStudio/releases/download/v02.07.01.57/Bambu_Studio_win-v02.07.01.57-20260601165745.zip',
      sha256: '95b210ff4cf4beb7ae3a7a36e341c0445f5567c50eb66ea5264061a8db296999',
      bytes: 461875461
    },
  },
  'bambustudio-2-7-1-62': {
    'linux-x64': {
      url: 'https://github.com/bambulab/BambuStudio/releases/download/v02.07.01.62/BambuStudio_ubuntu24.04-v02.07.01.62-20260616195227.AppImage',
      sha256: 'fa98b608532dfbbbb2b0931483aac41e57fb19c175a2cc7bd7d528d5e0fbb287',
      bytes: 227047928
    },
    'win32-x64': {
      url: 'https://github.com/bambulab/BambuStudio/releases/download/v02.07.01.62/Bambu_Studio_win-v02.07.01.62-20260616174358.zip',
      sha256: '790a6811ac480fa9cc6612ade6b9f74e3beec43a01be9340fbb6a04087226fdb',
      bytes: 461747465
    },
  },
  'bambustudio-2-8-0-50': {
    'linux-x64': {
      url: 'https://github.com/bambulab/BambuStudio/releases/download/v02.08.00.50/BambuStudio_ubuntu24.04-v02.08.00.50-20260625193201.AppImage',
      sha256: '246cb6b9ad93b4b4a65f631324dd7f098bf21198a2c39837e91aa6a0393e4dd4',
      bytes: 228583928
    },
    'win32-x64': {
      url: 'https://github.com/bambulab/BambuStudio/releases/download/v02.08.00.50/Bambu_Studio_win-v02.08.00.50-20260625193201.zip',
      sha256: '0eb6e5c52869c973efe4461c9c303fe1ac7e455a30f78119c6af3818e8c22b39',
      bytes: 465478706
    },
  },
  'bambustudio-2-8-1-55': {
    'linux-x64': {
      url: 'https://github.com/bambulab/BambuStudio/releases/download/v02.08.01.55/BambuStudio_ubuntu24.04-v02.08.01.55-20260715113557.AppImage',
      sha256: '225102433dbfcc475cbd79befa0453bb93f9f3cd15bb43848040a7fe2211c7de',
      bytes: 229009912
    },
    'win32-x64': {
      url: 'https://github.com/bambulab/BambuStudio/releases/download/v02.08.01.55/Bambu_Studio_win-v02.08.01.55-20260714203731.zip',
      sha256: '9a38cb628e7dcc74d7e7477d87f3ba2de5e1b98fd6f41ce5f6ca2afe8492a1cd',
      bytes: 468902312
    },
  },
}
