/**
 * The engines this build can install, and the pinned artifact for each.
 *
 * Distinct from the MANIFEST, which is what is installed right now. This is the
 * menu; that is the plate.
 *
 * Sourced from `docker/slicer-targets.mjs` so the container's baked-in set and
 * the runtime-installable set cannot diverge into two lists of engines that
 * disagree. The per-platform download pins live beside it in `ENGINE_ASSETS`,
 * regenerated by `docker/generate-engine-pins.mjs` rather than recorded by hand,
 * 14 artifacts, and a mistyped digit fails an install with a checksum error
 * that names nothing.
 *
 * A version with no asset for the running platform is not offered. That is not
 * hypothetical: Bambu publishes x86-64 only, so an arm64 Linux host can install
 * nothing here and must point `SLICER_SERVICE_URL` at a machine that can.
 */
import { z } from 'zod'
import { compareVersions } from './manifest.js'
import { launchStrategyNeedsSysroot, type SlicerEngineLaunchStrategy } from './launcher.js'
import { ENGINE_ASSETS } from '../../docker/engine-assets.mjs'
import { slicerTargets } from '../../docker/slicer-targets.mjs'

export interface EngineAsset {
  url: string
  sha256: string
  bytes: number
}

export interface CatalogueEngine {
  id: string
  label: string
  family: string
  version: string
  slicerName: string
  /** Bambu ships these as GitHub pre-releases; never selected as the default. */
  prerelease: boolean
  /** Flagged in the pinned list as the one a fresh host should install. */
  isDefault: boolean
  /** The artifact for the running platform. */
  asset: EngineAsset
  /**
   * Roughly what it occupies unpacked, for a UI that has to warn before a
   * download rather than after. Windows carries every DLL beside the exe and is
   * far larger than the Linux AppImage, which expects its libraries from the
   * shared runtime instead.
   */
  installBytes: number
}

/** Unpacked footprint, measured: 1.73 GB on Windows, 532 MB from the AppImage. */
/**
 * What an engine occupies once installed, per platform.
 *
 * The Windows figures are POST-PRUNE. Bambu's zip unpacks to ~1671 MB, of which
 * ~1145 MB is debug symbols the install drops (`prune-debug-files.ts`),
 * measured on a real install. Keep these in step with what that prune leaves,
 * or the engine manager's "about N GB on disk" over-promises to an operator
 * deciding whether a version fits.
 */
const INSTALL_BYTES: Record<string, number> = {
  'win32-x64': 530_000_000,
  'win32-arm64': 530_000_000,
  'linux-x64': 532_000_000
}

/**
 * The platform key whose artifact this host runs.
 *
 * Windows ARM takes the x64 build: measured on a Snapdragon X1E80100, it slices
 * under Prism emulation, including from session 0, producing gcode identical
 * to a native run.
 *
 * **Linux ARM depends on who is asking.** A bare ARM host has no way to run an
 * x86-64 engine, so the native strategy maps it to nothing. Our own container
 * does: it ships `qemu-user-static` and a baked x86-64 sysroot precisely so
 * arm64 works, which is what the README advertises. Answering "nothing" there
 * left an arm64 image with no installable engine and, once engines stopped
 * being baked in, no way to slice at all.
 */
export function assetPlatformKey(
  platform: NodeJS.Platform = process.platform,
  arch: string = process.arch,
  strategy: SlicerEngineLaunchStrategy = engineLaunchStrategy()
): string | null {
  if (platform === 'win32') return 'win32-x64'
  if (platform !== 'linux') return null
  if (arch === 'x64') return 'linux-x64'
  // The artifact is x86-64 either way; the container is what can run it.
  return arch === 'arm64' && strategy === 'container' ? 'linux-x64' : null
}

/**
 * Whether this host needs the shared Ubuntu runtime closure.
 *
 * Linux AND the native launch strategy. It used to be platform alone, which
 * made installing an engine inside our own container demand a closure the image
 * neither ships nor needs: the container runs engines through
 * `docker/bambu-studio-cli.sh` against OS packages (amd64) or its baked x86-64
 * sysroot (arm64). That mismatch is why Remove was a one-way door there.
 */
export function needsSharedSysroot(platform: NodeJS.Platform = process.platform): boolean {
  return launchStrategyNeedsSysroot(engineLaunchStrategy(), platform)
}

/** The strategy this process runs under. Read at call time, like the runtime asset config. */
export function engineLaunchStrategy(): SlicerEngineLaunchStrategy {
  return process.env.SLICER_ENGINE_LAUNCH === 'container' ? 'container' : 'native'
}

/**
 * Every engine installable on this host, in the pinned list's own order.
 *
 * That order is OLDEST first, and the comment here used to claim the opposite,
 * which is how the first-run install came to fetch Bambu Studio 2.6.0.51 on a
 * fresh container. Use {@link defaultCatalogueEngine} to pick one; do not take
 * the first entry.
 */
export function listCatalogue(
  platform: NodeJS.Platform = process.platform,
  arch: string = process.arch,
  strategy: SlicerEngineLaunchStrategy = engineLaunchStrategy()
): CatalogueEngine[] {
  const key = assetPlatformKey(platform, arch, strategy)
  if (!key) return []
  const installBytes = INSTALL_BYTES[key] ?? 0

  return slicerTargets
    .map((target) => {
      const asset = (ENGINE_ASSETS as Record<string, Record<string, EngineAsset | undefined>>)[target.id]?.[key]
      if (!asset) return null
      return {
        id: target.id,
        label: target.label,
        family: target.family,
        version: target.version,
        slicerName: target.slicerName,
        prerelease: target.prerelease === true,
        isDefault: target.isDefault === true,
        asset,
        installBytes
      } satisfies CatalogueEngine
    })
    .filter((entry): entry is CatalogueEngine => entry !== null)
}

/**
 * The engine a host with none should install.
 *
 * One rule, so the manifest's default and the first-run install cannot disagree:
 * the explicitly flagged target, else the NEWEST stable one. A beta must never
 * become the default, including through the fallback.
 *
 * The fallback compares versions rather than taking the first stable entry:
 * the pinned list is oldest-first, and "first stable" silently meant "oldest
 * stable".
 */
export function defaultCatalogueEngine(
  platform: NodeJS.Platform = process.platform,
  arch: string = process.arch,
  strategy: SlicerEngineLaunchStrategy = engineLaunchStrategy()
): CatalogueEngine | null {
  const installable = listCatalogue(platform, arch, strategy)
  const flagged = installable.find((engine) => engine.isDefault && !engine.prerelease)
  if (flagged) return flagged
  return installable
    .filter((engine) => !engine.prerelease)
    .sort((a, b) => compareVersions(b.version, a.version))[0] ?? null
}

export function findCatalogueEngine(
  id: string,
  platform: NodeJS.Platform = process.platform,
  arch: string = process.arch
): CatalogueEngine | null {
  return listCatalogue(platform, arch).find((engine) => engine.id === id) ?? null
}

/**
 * The engine a fresh install should get: the newest STABLE one.
 *
 * Derived rather than named, so publishing a new release does not need a second
 * edit here to take effect, and so a beta can never become what a fresh install
 * silently runs.
 */
export function latestStableEngine(
  platform: NodeJS.Platform = process.platform,
  arch: string = process.arch
): CatalogueEngine | null {
  const stable = listCatalogue(platform, arch).filter((engine) => !engine.prerelease)
  return stable.at(-1) ?? null
}

/**
 * The shared Linux runtime closure, from configuration.
 *
 * Deliberately NOT accepted from a request. This service downloads the archive
 * and the engine executes against the libraries inside it, so a caller-supplied
 * URL is arbitrary code execution, and `SLICER_SERVICE_TOKEN` is optional, so
 * "caller" can mean anyone who reaches the port.
 *
 * Null when unset, which is the container images' normal state: they bake their
 * closure in at build time and never install one at runtime.
 */
export function configuredSharedRuntime(): EngineAsset | null {
  const parsed = z.object({
    url: z.string().url(),
    sha256: z.string().regex(/^[0-9a-f]{64}$/),
    bytes: z.coerce.number().int().positive()
    // Read from `process.env` at CALL time, not from the module-load `env`
    // snapshot. A host can only compute this after its database is up (the
    // origin comes from the installed licence key), which is necessarily later
    // than the import that would freeze it -- the native app loads this module
    // during boot and calls `configureSharedRuntime` afterwards. Reading the
    // snapshot made every Linux engine install fail with "this deployment is
    // not configured to fetch them" while the variables were in fact set.
  }).safeParse({
    url: process.env.SLICER_RUNTIME_URL,
    sha256: process.env.SLICER_RUNTIME_SHA256,
    bytes: process.env.SLICER_RUNTIME_BYTES
  })
  if (!parsed.success) {
    if (process.env.SLICER_RUNTIME_URL) {
      console.warn('[engines] SLICER_RUNTIME_* is set but incomplete or malformed; ignoring it.')
    }
    return null
  }
  return parsed.data
}
