/**
 * Managed-bridge mode primitives.
 *
 * A self-hosted server enters managed-bridge mode by setting `MANAGED_BRIDGE`.
 * In that mode the server provisions and owns a single bundled bridge: it
 * auto-pairs a bridge that presents the matching provisioning token (see
 * `bridge-pairing.ts`), the web app hides every bridge-management surface, and
 * connectivity failures speak about an internal "printer connection service"
 * rather than a "bridge" the operator manages.
 *
 * The provisioning token is generated by the API and never set by an operator:
 * the API writes a random token to `MANAGED_BRIDGE_TOKEN_FILE` (a path shared
 * with the bundled bridge over a mounted volume), and the bridge reads it from
 * the same path to authenticate its first registration. Security comes from the
 * token being unknown to anyone who can't read that private file, so it holds
 * regardless of how the API port is exposed.
 *
 * This module depends only on `env`, `crypto`, and `fs`; keep it free of imports
 * that would pull in the bridge session manager so the outage-message helper can
 * be used from deep transport code without an import cycle.
 */
import { createHash, randomBytes, timingSafeEqual } from 'node:crypto'
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { env } from './env.js'

/** True when this server provisions and owns a single bundled bridge. */
export function isManagedBridgeMode(): boolean {
  return env.MANAGED_BRIDGE
}

/**
 * Returns the managed-bridge provisioning token, creating it on first use.
 * Reads `MANAGED_BRIDGE_TOKEN_FILE`; if it is absent or empty, generates a
 * random token and writes it (owner-only). Returns null when not in managed
 * mode — there is no token to issue. The API ensures this at startup so the
 * bundled bridge can read the file before it first registers.
 */
export function ensureManagedBridgeToken(): string | null {
  if (!isManagedBridgeMode()) return null
  const file = env.MANAGED_BRIDGE_TOKEN_FILE
  try {
    const existing = readFileSync(file, 'utf8').trim()
    if (existing) return existing
  } catch {
    // Missing or unreadable — fall through and create it.
  }
  const token = randomBytes(32).toString('base64url')
  mkdirSync(path.dirname(file), { recursive: true })
  writeFileSync(file, token, { mode: 0o600 })
  return token
}

/**
 * Constant-time comparison of a bridge-supplied provisioning token against the
 * server's token. Both sides are hashed first so the timing-safe compare runs
 * over equal-length buffers. Returns false when no token is configured.
 */
export function managedBridgeSecretMatches(candidate: string, expected: string | null | undefined): boolean {
  if (!expected) return false
  const candidateHash = Buffer.from(createHash('sha256').update(candidate).digest('hex'), 'utf8')
  const expectedHash = Buffer.from(createHash('sha256').update(expected).digest('hex'), 'utf8')
  if (candidateHash.length !== expectedHash.length) return false
  return timingSafeEqual(candidateHash, expectedHash)
}

/**
 * User-facing copy for a "the bridge isn't reachable" failure. In managed-bridge
 * mode the operator never thinks in terms of a bridge they manage, so the
 * message describes an internal service being offline; otherwise the caller's
 * existing bridge-centric wording is preserved.
 */
export function bridgeUnavailableMessage(fallback = 'Bridge is not connected'): string {
  return isManagedBridgeMode()
    ? 'The printer connection service is offline. Check that all PrintStream services are running.'
    : fallback
}
