/**
 * Persistent cache for client-rendered STL/STEP preview thumbnails.
 *
 * STL and STEP library files carry no embedded image, and neither the API nor the
 * bridge ships a 3D renderer, so the web client renders a small iso snapshot with
 * Three.js (see `apps/web/src/plugins/model-studio/lib/meshThumbnail.ts`). Without a
 * persistent cache that render — and, for STEP, an expensive server-side OCCT
 * tessellation behind `/mesh` — repeats on every page load. This module lets the
 * client upload the rendered PNG once so subsequent views (for every client and
 * session) are served the bytes directly through `GET /api/library/:id/thumbnail`.
 *
 * The cache is content-addressed on `(ownerBridgeId, storedPath)`. `storedPath` is
 * collision-free per uploaded version, so saving a new version of a file lands in a
 * fresh cache slot and the old render is left to TTL pruning — i.e. thumbnails
 * regenerate exactly when the file content changes, and not otherwise.
 */
import path from 'node:path'
import { mkdir, readFile, readdir, rm, stat, writeFile } from 'node:fs/promises'
import { createHash } from 'node:crypto'
import { libraryDir } from './library-paths.js'

const meshThumbnailCacheDir = path.join(libraryDir, '_mesh-thumbnail-cache')

/**
 * Cache layout version. Bump when the client render changes materially (camera
 * angle, framing, mesh colour) so stale-looking thumbnails are invalidated even
 * for files whose bytes never change. Old version directories become orphaned and
 * are removed by TTL pruning.
 */
const MESH_THUMBNAIL_CACHE_VERSION = 1

/** Mirrors the bridge derived-cache retention so a single sweep keeps both bounded. */
const MESH_THUMBNAIL_CACHE_TTL_MS = 90 * 24 * 60 * 60 * 1000

/**
 * Hard cap on an accepted thumbnail. A 256x256 PNG snapshot is tens of KB; this
 * leaves generous headroom while bounding what an authenticated viewer can write.
 */
export const MESH_THUMBNAIL_MAX_BYTES = 512 * 1024

const PNG_MAGIC = Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a])

type MeshThumbnailFile = { ownerBridgeId?: string | null; storedPath: string }

/** True when `buffer` starts with the 8-byte PNG signature. */
export function isLikelyPng(buffer: Buffer): boolean {
  return buffer.length >= PNG_MAGIC.length && buffer.subarray(0, PNG_MAGIC.length).equals(PNG_MAGIC)
}

function cacheFilePath(file: MeshThumbnailFile): string {
  const digest = createHash('sha256')
    .update(`${file.ownerBridgeId ?? ''}\0${file.storedPath}`)
    .digest('hex')
  return path.join(meshThumbnailCacheDir, `v${MESH_THUMBNAIL_CACHE_VERSION}`, `${digest}.png`)
}

/** Cached PNG bytes for a mesh file, or `null` when nothing has been rendered yet. */
export async function readMeshThumbnailCache(file: MeshThumbnailFile): Promise<Buffer | null> {
  try {
    return await readFile(cacheFilePath(file))
  } catch {
    return null
  }
}

/** Persist a client-rendered PNG for a mesh file. */
export async function writeMeshThumbnailCache(file: MeshThumbnailFile, png: Buffer): Promise<void> {
  const target = cacheFilePath(file)
  await mkdir(path.dirname(target), { recursive: true })
  await writeFile(target, png)
}

/**
 * Remove cached thumbnails older than `maxAgeMs`. The cache self-heals — a pruned
 * thumbnail is regenerated by the next viewer — so retention only needs to bound
 * disk for files that are no longer being looked at.
 */
export async function pruneMeshThumbnailCache(maxAgeMs = MESH_THUMBNAIL_CACHE_TTL_MS): Promise<{ removedFiles: number }> {
  const cutoff = Date.now() - maxAgeMs
  let removedFiles = 0
  const versionDirs = await readdir(meshThumbnailCacheDir, { withFileTypes: true }).catch(() => [])
  for (const versionDir of versionDirs) {
    if (!versionDir.isDirectory()) continue
    const dirPath = path.join(meshThumbnailCacheDir, versionDir.name)
    const entries = await readdir(dirPath, { withFileTypes: true }).catch(() => [])
    for (const entry of entries) {
      if (!entry.isFile()) continue
      const filePath = path.join(dirPath, entry.name)
      const info = await stat(filePath).catch(() => null)
      if (info && info.mtimeMs < cutoff) {
        await rm(filePath, { force: true }).catch(() => undefined)
        removedFiles += 1
      }
    }
  }
  return { removedFiles }
}
