/**
 * Portable files and descriptive metadata stored inside a 3MF project's `Auxiliaries/` tree.
 *
 * The file list is complete state when present on a `SceneEdit`: a save replaces the five folders
 * this module owns while preserving unknown auxiliary folders. File bytes use base64 because the
 * same edit can still cross the JSON API boundary, even though both current editor hosts bake in
 * the browser.
 */
import { z } from 'zod'

export const PROJECT_AUXILIARY_CATEGORIES = [
  'Model Pictures',
  'Bill of Materials',
  'Assembly Guide',
  'Others',
  'Profile Pictures'
] as const

export type ProjectAuxiliaryCategory = typeof PROJECT_AUXILIARY_CATEGORIES[number]

/** Maximum decoded size of one user attachment. */
export const MAX_PROJECT_AUXILIARY_FILE_BYTES = 16 * 1024 * 1024
/** Maximum decoded size of the complete managed auxiliary tree. */
export const MAX_PROJECT_AUXILIARY_TOTAL_BYTES = 64 * 1024 * 1024

const BASE64_PATTERN = /^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/
const SAFE_FILE_NAME_PATTERN = /^[^/\\\0]+$/

/** Conservative decoded length without allocating the decoded bytes. */
export function decodedBase64Length(value: string): number {
  if (value.length === 0) return 0
  const padding = value.endsWith('==') ? 2 : value.endsWith('=') ? 1 : 0
  return Math.floor((value.length * 3) / 4) - padding
}

/** Decode attachment bytes without taking a dependency on either Node's Buffer or the DOM. */
export function decodeProjectAuxiliaryBase64(value: string): Uint8Array {
  const runtime = globalThis as unknown as {
    atob?: (encoded: string) => string
    Buffer?: { from(encoded: string, encoding: string): Uint8Array }
  }
  if (typeof runtime.atob === 'function') {
    const binary = runtime.atob(value)
    return Uint8Array.from(binary, (character) => character.charCodeAt(0))
  }
  if (runtime.Buffer) return new Uint8Array(runtime.Buffer.from(value, 'base64'))
  throw new Error('This environment cannot decode project attachments')
}

/** Encode attachment bytes in bounded chunks so a large image cannot overflow the call stack. */
export function encodeProjectAuxiliaryBase64(bytes: Uint8Array): string {
  const runtime = globalThis as unknown as {
    btoa?: (raw: string) => string
    Buffer?: { from(bytes: Uint8Array): { toString(encoding: string): string } }
  }
  if (runtime.Buffer) return runtime.Buffer.from(bytes).toString('base64')
  if (typeof runtime.btoa === 'function') {
    let raw = ''
    const chunkSize = 0x8000
    for (let offset = 0; offset < bytes.length; offset += chunkSize) {
      raw += String.fromCharCode(...bytes.subarray(offset, offset + chunkSize))
    }
    return runtime.btoa(raw)
  }
  throw new Error('This environment cannot encode project attachments')
}

export const projectAuxiliaryFileSchema = z.object({
  category: z.enum(PROJECT_AUXILIARY_CATEGORIES),
  name: z.string().trim().min(1).max(255)
    .regex(SAFE_FILE_NAME_PATTERN, 'Attachment names must not contain path separators'),
  contentBase64: z.string().regex(BASE64_PATTERN, 'Attachment content must be valid base64')
    .refine(
      (value) => decodedBase64Length(value) <= MAX_PROJECT_AUXILIARY_FILE_BYTES,
      `An attachment must be at most ${MAX_PROJECT_AUXILIARY_FILE_BYTES} bytes`
    ),
  /** BambuStudio allows one cover in each picture folder. */
  cover: z.boolean().optional()
})
export type ProjectAuxiliaryFile = z.infer<typeof projectAuxiliaryFileSchema>

export const projectAuxiliaryMetadataSchema = z.object({
  modelName: z.string().max(500).default(''),
  modelAuthor: z.string().max(500).default(''),
  modelDescription: z.string().max(10_000).default(''),
  modelId: z.string().max(500).default(''),
  profileName: z.string().max(500).default(''),
  profileAuthor: z.string().max(500).default(''),
  profileDescription: z.string().max(10_000).default('')
})
export type ProjectAuxiliaryMetadata = z.infer<typeof projectAuxiliaryMetadataSchema>

export const projectAuxiliariesSchema = z.object({
  files: z.array(projectAuxiliaryFileSchema).max(200),
  metadata: projectAuxiliaryMetadataSchema,
  /** PNG derivatives of the selected model cover, generated by the browser. */
  coverThumbnails: z.object({
    threeMf: z.string().regex(BASE64_PATTERN),
    small: z.string().regex(BASE64_PATTERN),
    middle: z.string().regex(BASE64_PATTERN)
  }).optional()
}).superRefine((value, context) => {
  const names = new Set<string>()
  const coverCategories = new Set<ProjectAuxiliaryCategory>()
  let totalBytes = 0

  value.files.forEach((file, index) => {
    const key = `${file.category}/${file.name}`.toLowerCase()
    if (names.has(key)) {
      context.addIssue({ code: z.ZodIssueCode.custom, path: ['files', index, 'name'], message: 'Attachment names must be unique within a folder' })
    }
    names.add(key)
    totalBytes += decodedBase64Length(file.contentBase64)

    if (file.cover) {
      if (file.category !== 'Model Pictures' && file.category !== 'Profile Pictures') {
        context.addIssue({ code: z.ZodIssueCode.custom, path: ['files', index, 'cover'], message: 'Only project pictures can be used as covers' })
      }
      if (coverCategories.has(file.category)) {
        context.addIssue({ code: z.ZodIssueCode.custom, path: ['files', index, 'cover'], message: 'A picture folder can have only one cover' })
      }
      coverCategories.add(file.category)
    }
  })

  if (value.files.some((file) => file.category === 'Model Pictures' && file.cover) && !value.coverThumbnails) {
    context.addIssue({ code: z.ZodIssueCode.custom, path: ['coverThumbnails'], message: 'A model cover requires generated thumbnails' })
  }
  if (value.coverThumbnails) {
    totalBytes += decodedBase64Length(value.coverThumbnails.threeMf)
      + decodedBase64Length(value.coverThumbnails.small)
      + decodedBase64Length(value.coverThumbnails.middle)
  }

  if (totalBytes > MAX_PROJECT_AUXILIARY_TOTAL_BYTES) {
    context.addIssue({ code: z.ZodIssueCode.custom, path: ['files'], message: 'Project attachments exceed the 64 MB limit' })
  }
})
export type ProjectAuxiliaries = z.infer<typeof projectAuxiliariesSchema>

/** File extensions accepted by BambuStudio's five fixed folders. */
export const PROJECT_AUXILIARY_ACCEPT: Record<ProjectAuxiliaryCategory, readonly string[]> = {
  'Model Pictures': ['.png', '.jpg', '.jpeg', '.bmp'],
  'Bill of Materials': ['.xls', '.xlsx', '.pdf'],
  'Assembly Guide': ['.pdf'],
  Others: ['.txt'],
  'Profile Pictures': ['.png', '.jpg', '.jpeg', '.bmp']
}

/** Whether a name has an extension accepted by its destination folder. */
export function projectAuxiliaryFileNameAllowed(category: ProjectAuxiliaryCategory, name: string): boolean {
  const lower = name.toLowerCase()
  return PROJECT_AUXILIARY_ACCEPT[category].some((extension) => lower.endsWith(extension))
}
